version: '3'
services:
  myapp:
    stop_signal: SIGINT
    ports:
      - "8000:8000"

    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - ./models:/soloist/models
      - ./data:/soloist/data

    working_dir: /soloist
    image: myapp_image
    stdin_open: true 
    tty: true